
services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-network

  boot-app:
    image: thanhtule/chatback:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGO_URI=mongodb://mongo:27017/chat
    depends_on:
      - mongo
    networks:
      - app-network


  react-service:
    image: thanhtule/chatback:latest
    build:
      context: ./front-chat
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network


volumes:
  mongo-db:

networks:
  app-network:
    driver: bridge


# docker compose build
# docker login
# docker compose push